# Introduction
## Help

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
import zipfile

# Initial Questions
1. What do we want to know about airline on-time performance?
2. How will the answer be useful in decision making?

# Data Specific Questions
**1. How does on-time performance vary across carrier, airports, time, day, maybe aircraft?**
   
    -  What's the overall distribution of any flight delays? 
    -  What airline has the best and worst on-time performance? 
    -  How do routes (short/long) correlate with performance? 
    -  What departure time windows have the least amount of delays? Most amount of delays? 
    -  What is the average delay per airport? per airline? per airport & airline? 
    - What percentage of flights leave on-time? Delayed? 
    -  What time ranges have the highest/lowest delays? 
    -How many flights per day? 
        - By airport? By carrier? 
    -What is the average aircraft turnaround time by carrier? (I'd think we'd have to subtract any weather, security, or NAS delays because those are not impacted their ability to get the aircraft ready for the next flight) 
    

**2. What delay propagation patterns can we draw?**

    - Is there recovery or do they compound / propagate? 
            - Are some airlines better at recovering than others? 
        - What information can we draw from taxi times? Thinking about traffic jams at the runways due to built up delays
    - What percent of flights are delayed 15, 30, 60+ minutes? 
    - What is the % chance that a late arrival will cause the next flight to also be late 
    - What is the average total time per day in delays a carrier has? 
    - What correlations are there between delays and cancelations (mainly downstream, think about how a major storm could cause mass cancellations in a short period of time)? 

**3. What factors have the greatest effect on on-time performance**
   
    - Weather 
        - What is the average number of delays per day due to weather?
        - What percentage of days are due to weather?
        - Which airports have the highest/most frequent weather delays?
        - How much time is the average weather delay?
    - Secuirty 
        - What percentage of delays are due to security issues?
        - How much time is the average security delay? 
    - Carrier 
        - Which carriers have the highest delays?
        - How much time is the average carrier delay
    - National Aviation System (Delay within control of ATC, not airline) 
        - Which airports have the most/highest delays due to NAS?
        - How much time is the average NAS delau
        - What is the total number 

4. What is the overall cost of delays?
    -Fuel, labor, etc. 

6. What is the impact to customers?
    - Which airports should customers expect delays
    - What percent of flights are delayed 15, 30, 60+ minutes?


## Brandon Analysis Questions
    -  How do routes correlate with performance? 
    - What are the max, min, and average flight times? Is there a relationships to flight length and delays
    -  What departure time windows have the least amount of delays? Most amount of delays? 
    -  What time ranges have the highest/lowest delays? 
    -How many flights per day? 
        - By airport? By carrier? 
    - How resilient is each carrier to delay shocks?
        - What % of flights recover to on-time after a delay?
    - What is the % chance that a late arrival will cause the next flight to also be late T
    - What is the average total time per day in delays a carrier has? 
    - Weather 
        - What is the average number of delays per day due to weather?
        - What percentage of days are due to weather?
        - Which airports have the highest/most frequent weather delays?
        - How much time is the average weather delay?
    - Secuirty 
        - What percentage of delays are due to security issues?
        - How much time is the average security delay? 
    - Are taxi times leading indicators of airport congestion?
        - What is the relationship between taxi out times and departure delays (Wheels off)
    
## Trace Analysis Questions
    -  What's the overall distribution of any flight delays? 
    - What airports have the highest delays?
    -  What airline has the best and worst on-time performance? 
    -  What is the average delay per airport? per airline? per airport & airline? 
    - What percentage of flights leave on-time? Delayed? 
    -What is the average aircraft turnaround time by carrier? (I'd think we'd have to subtract any weather, security, or NAS delays because those are not impacted their ability to get the aircraft ready for the next flight) 
    - What percent of flights are delayed 15, 30, 60+ minutes? 
    - What is the % chance that a late arrival will cause the next flight to also be late 
    - What correlations are there between delays and cancelations (mainly downstream, think about how a major storm could cause mass cancellations in a short period of time)? 
    - Carrier 
        - Which carriers have the highest delays?
        - How much time is the average carrier delay
    - National Aviation System (Delay within control of ATC, not airline) 
        - Which airports have the most/highest delays due to NAS?
        - How much time is the average NAS delay?
    - What is the likelyhood of a delay based on airline, airport, and time of day?
    - What aircraft have the highest carrier delays?
    - What day of the week has the highest delays?

## Amibtion
- What is the cost to airlines due to delays? Per day? Per Year?
- 


        
# Source Data
United States Department of Transportation - U.S. Buerau of Transportation Statistics

# Features Needed
### 1. Date

### 2. Time of Day

### 3. Carrier
- American
- United
- Delta
- Southwest
- Alaska
- JetBlue
- Spirit
- Frontier

### 5. Airport (Departure)
- Dallas Fort-Worth (DFW) **1**
- Atlanta (ATL)           **2**
- Los Angeles (LAX)       **3**
- New York                **6**
  - JFK
- Miami (MIA)             **8**
- Chicago O'Hare (OHD)    **4**
- Phoenix (PHX)           **7**
- Denver (DEN)            **5**
- San Franscisco (SFO)
- Washington D.C.
  - Dulles (IAD)

**I was thinking we could just narrow it down to 5-10 airports but since we have the airport IDs in the data, I don't entirely see the benefit of just picking 10 other than maybe lessening the complexity or size of the data. Maybe we could just do some groupings by U.S. region? Open to suggestions**


### 7. Airport (Arrival) / Destination

### 8. Reason For Delay
- Weather
- Carrier
- Security
- Late Aircraft
- National Aviation System (NAS)

**we can leave these split up into their own feature**

### 9. Tail Number

### 10. Elapsed Time

### 11. State

### 12. Wheels Up

### 13. Wheel Down

### 14. Taxi Time (We could create a column that sums up taxi out and taxi in. However, taxi out could be an important variable for assessing NAS delays)

# 1. Initial Load & Reconniassance 
## Questions to Answer
1. Tidy or not?
2. Entities, Attributes, Observations?
3. Variable Types?
4. Shape & scale?
5. Any obvious problems?

**I will add a table of feature names and a brief description for each so it's easy to follow the table**

### Hypothessis
- Relationships worth exploring
    - Numeric
    - Categorical
    - Numeric vs Categorical
    - Numeric vs Numeric 
    -  on-time performance vs. time of day
    -  on-time performance vs carrier
    -  on-time performance vs airport
    -  Carrier vs % of flights delayed
    -  Carrier vs departure / arrival delays

-

In [3]:
#Main dataset
z_folder = Path("../data/Raw/bts_on_time")
output_folder = Path("../data/extracted")
output_folder.mkdir(exist_ok=True)

for z in z_folder.glob("*.zip"):
    with zipfile.ZipFile(z, 'r') as zf:
        for f in zf.namelist():
            if f.endswith(".csv"):
                zf.extract(f, output_folder)

csv_folder = Path("../data/extracted")
dfs = [pd.read_csv(f, low_memory=False) for f in csv_folder.glob("*.csv")]
df_all = pd.concat(dfs, ignore_index=True)
df_all
# df_path = Path("../data/Raw/Source_Data.zip")
# df_main = pd.read_csv(df_path, compression="zip", parse_dates=["FL_DATE"], low_memory=False)
# df_main

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2022,4,11,23,3,2022-11-23,OH,20397,OH,N513AE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022,4,11,27,7,2022-11-27,OH,20397,OH,N538EG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022,4,11,28,1,2022-11-28,OH,20397,OH,N522AE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022,4,11,29,2,2022-11-29,OH,20397,OH,N526EA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022,4,11,30,3,2022-11-30,OH,20397,OH,N526EA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35417935,2022,2,6,21,2,2022-06-21,DL,19790,DL,N345DN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35417936,2022,2,6,21,2,2022-06-21,DL,19790,DL,N345DN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35417937,2022,2,6,22,3,2022-06-22,DL,19790,DL,N117DX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35417938,2022,2,6,22,3,2022-06-22,DL,19790,DL,N117DX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35417939,2022,2,6,23,4,2022-06-23,DL,19790,DL,N396DN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df_aircraft = pd.read_csv("../data/Raw/Aircraft.csv")
df_aircraft

,N-NUMBER,MFR MDL CODE,MFR,MODEL,NO-SEATS
0,100,7100510,PIPER,J3C-65,2
1,10000,2130004,CIRRUS DESIGN CORP,SR22T,5
2,10001,9601202,WACO,ASO,3
3,10004,2072738,CESSNA,T182T,4
4,10006,1152020,BEECH,D-45 (T-34B),4
...,...,...,...,...,...
308193,9ZS,5760102,MOLINO OY,PIK-20E,1
308194,9ZT,2130001,CIRRUS DESIGN CORP,SR22,4
308195,9ZU,7101828,PIPER,PA-18-150,2
308196,9ZV,1181511,BELL,206B,5
308197,9ZX,05655US,POBEREZNY PAUL H,HIPERLIGHT SNS-8,1

In [26]:
df_main["TAIL_NUM"] = df_main["TAIL_NUM"].str.lstrip("N")
df_aircraft = df_aircraft.drop(columns='MFR MDL CODE')
#Changing features names to be more clear
df_mod = df_main.rename(columns={
    'FL_DATE': 'Flight Date',
    'OP_CARRIER': 'Carrier',
    'TAIL_NUM': 'Tail Number',
    'OP_CARRIER_FL_NUM': 'Flight Number',
    'ORIGIN': 'Origin Airport',
    'ORIGIN_CITY_NAME': 'Origin City',
    'ORIGIN_STATE_NM': 'Origin State',
    'DEST': 'Destination Airport',
    'DEST_CITY_NAME': 'Destination City',
    'DEST_STATE_NM': 'Destination State'
    
})

#Changing feature names for aircraft DF
mod_aircraft = df_aircraft.rename(columns= {
    'N-NUMBER': 'Tail_Number',
    'MFR': 'Manufacturer',
    'NO-SEATS': 'Number_of_Seats'
})
mod_aircraft

df_merged = df_mod.merge(mod_aircraft, on='Tail_Number', how='left')
df_merged

,Flight_Date,Carrier,Tail_Number,Flight_Number,Origin_Airport,Origin_City,Origin_State,Destination_Airport,Destination_City,Destination_State,...,TOTAL_ADD_GTIME,LONGEST_ADD_GTIME,DIV_AIRPORT_LANDINGS,DIV_REACHED_DEST,DIV_ACTUAL_ELAPSED_TIME,DIV_ARR_DELAY,DIV_DISTANCE,Manufacturer,MODEL,Number_of_Seats
0,2025-01-01,AA,101NN,164,SFO,"San Francisco, CA",California,JFK,"New York, NY",New York,...,NaN,NaN,0,NaN,NaN,NaN,NaN,AIRBUS INDUSTRIE,A321-231,379.0
1,2025-01-01,AA,101NN,76,JFK,"New York, NY",New York,SFO,"San Francisco, CA",California,...,NaN,NaN,0,NaN,NaN,NaN,NaN,AIRBUS INDUSTRIE,A321-231,379.0
2,2025-01-01,AA,102UW,3244,SAT,"San Antonio, TX",Texas,CLT,"Charlotte, NC",North Carolina,...,NaN,NaN,0,NaN,NaN,NaN,NaN,AIRBUS INDUSTRIE,A320-214,182.0
3,2025-01-01,AA,103NN,185,JFK,"New York, NY",New York,LAX,"Los Angeles, CA",California,...,NaN,NaN,0,NaN,NaN,NaN,NaN,AIRBUS,A321-231,379.0
4,2025-01-01,AA,103NN,2455,BOS,"Boston, MA",Massachusetts,LAX,"Los Angeles, CA",California,...,NaN,NaN,0,NaN,NaN,NaN,NaN,AIRBUS,A321-231,379.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539742,2025-01-31,YX,979RP,4513,LGA,"New York, NY",New York,CLE,"Cleveland, OH",Ohio,...,NaN,NaN,0,NaN,NaN,NaN,NaN,EMBRAER,ERJ 170-100 SE,70.0
539743,2025-01-31,YX,979RP,4654,LGA,"New York, NY",New York,SDF,"Louisville, KY",Kentucky,...,NaN,NaN,0,NaN,NaN,NaN,NaN,EMBRAER,ERJ 170-100 SE,70.0
539744,2025-01-31,YX,979RP,4654,SDF,"Louisville, KY",Kentucky,LGA,"New York, NY",New York,...,NaN,NaN,0,NaN,NaN,NaN,NaN,EMBRAER,ERJ 170-100 SE,70.0
539745,2025-01-31,YX,979RP,4666,CVG,"Cincinnati, OH",Kentucky,LGA,"New York, NY",New York,...,NaN,NaN,0,NaN,NaN,NaN,NaN,EMBRAER,ERJ 170-100 SE,70.0
539746,2025-01-31,YX,979RP,4787,LGA,"New York, NY",New York,GSP,"Greer, SC",South Carolina,...,NaN,NaN,0,NaN,NaN,NaN,NaN,EMBRAER,ERJ 170-100 SE,70.0

In [18]:
df.columns
df.info()
df.describe()
df.shape()

mod_df = df.drop(columns=['', 
mod_df

# col_names = {
#     'Column Name': [
#         'FL_DATE',                 
#         'OP_CARRIER',               
#         'TAIL_NUM',            
#         'OP_CARRIER_FL_NUM',   
#         'ORIGIN',              
#         'ORIGIN_CITY_NAME',      
#         'ORIGIN_STATE_NM',       
#         'DEST',                  
#         'DEST_CITY_NAME',        
#         'DEST_STATE_NM',         
#         'DEP_TIME',              
#         'DEP_DELAY',             
#         'DEP_DELAY_NEW',         
#         'TAXI_OUT',              
#         'WHEELS_OFF',            
#         'WHEELS_ON',             
#         'TAXI_IN',               
#         'ARR_TIME',             
#         'ARR_DELAY',            
#         'ARR_DELAY_NEW',        
#         'CANCELLED',            
#         'CANCELLATION_CODE',    
#         'DIVERTED',             
#         'ACTUAL_ELAPSED_TIME',  
#         'AIR_TIME',             
#         'FLIGHTS',              
#         'DISTANCE',             
#         'DISTANCE_GROUP',      
#         'CARRIER_DELAY',        
#         'WEATHER_DELAY',        
#         'NAS_DELAY',            
#         'SECURITY_DELAY',       
#         'LATE_AIRCRAFT_DELAY',  
#         'FIRST_DEP_TIME',       
#         'TOTAL_ADD_GTIME',      
#         'LONGEST_ADD_GTIME',    
#         'DIV_AIRPORT_LANDINGS',     
#         'DIV_REACHED_DEST',         
#         'DIV_ACTUAL_ELAPSED_TIME',  
#         'DIV_ARR_DELAY',            
#         'DIV_DISTANCE', 
#     ],
#     'Description': [
#         'Flight Date',
#         'Carrier',
#         'Aircraft Tail Number',
#         'Flight Number',
#         'Origin Airport',
#         'Origin City',
#         'Origin State',
#         'Destination Airport',
#         'Destination City',
#         'Destination State',
#         'Departure Time',
#         'Scheduled Dep. Time - Actual Dep. Time',
#         'kdkdkdkd',
#         'Amount of time to taxi to for takeoff',
#         'Takeoff Time',
#         'Landing Time',
#         'Amount of time to taxi to the gate',
#         'Arrival Time',
#         'Difference in minutes between scheduled and actual arrival time',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#         'jndcjdnc',
#     ]
# }
# col_df = pd.DataFrame(col_names)
# col_df

                Column Name                                        Description
0                   FL_DATE                                        Flight Date
1                OP_CARRIER                                            Carrier
2                  TAIL_NUM                               Aircraft Tail Number
3         OP_CARRIER_FL_NUM                                      Flight Number
4                    ORIGIN                                     Origin Airport
5          ORIGIN_CITY_NAME                                        Origin City
6           ORIGIN_STATE_NM                                       Origin State
7                      DEST                                Destination Airport
8            DEST_CITY_NAME                                   Destination City
9             DEST_STATE_NM                                  Destination State
10                 DEP_TIME                                     Departure Time
11                DEP_DELAY             Scheduled Dep. Time - Actual Dep. Time
12            DEP_DELAY_NEW                                           kdkdkdkd
13                 TAXI_OUT              Amount of time to taxi to for takeoff
14               WHEELS_OFF                                       Takeoff Time
15                WHEELS_ON                                       Landing Time
16                  TAXI_IN                 Amount of time to taxi to the gate
17                 ARR_TIME                                       Arrival Time
18                ARR_DELAY  Difference in minutes between scheduled and ac...
19            ARR_DELAY_NEW                                           jndcjdnc
20                CANCELLED                                           jndcjdnc
21        CANCELLATION_CODE                                           jndcjdnc
22                 DIVERTED                                           jndcjdnc
23      ACTUAL_ELAPSED_TIME                                           jndcjdnc
24                 AIR_TIME                                           jndcjdnc
25                  FLIGHTS                                           jndcjdnc
26                 DISTANCE                                           jndcjdnc
27           DISTANCE_GROUP                                           jndcjdnc
28            CARRIER_DELAY                                           jndcjdnc
29            WEATHER_DELAY                                           jndcjdnc
30                NAS_DELAY                                           jndcjdnc
31           SECURITY_DELAY                                           jndcjdnc
32      LATE_AIRCRAFT_DELAY                                           jndcjdnc
33           FIRST_DEP_TIME                                           jndcjdnc
34          TOTAL_ADD_GTIME                                           jndcjdnc
35        LONGEST_ADD_GTIME                                           jndcjdnc
36     DIV_AIRPORT_LANDINGS                                           jndcjdnc
37         DIV_REACHED_DEST                                           jndcjdnc
38  DIV_ACTUAL_ELAPSED_TIME                                           jndcjdnc
39            DIV_ARR_DELAY                                           jndcjdnc
40             DIV_DISTANCE                                           jndcjdnc

In [3]:
#Changing features names to be more clear
mod_df = df.rename(columns={
    'FL_DATE': 'Flight Date',
    'OP_CARRIER': 'Carrier',
    'TAIL_NUM': 'Tail Number',
    'OP_CARRIER_FL_NUM': 'Flight Number',
    'ORIGIN': 'Origin Airport',
    'ORIGIN_CITY_NAME': 'Origin City',
    'ORIGIN_STATE_NM': 'Origin State',
    'DEST': 'Destination Airport',
    'DEST_CITY_NAME': 'Destination City',
    'DEST_STATE_NM': 'Destination State'
    
})

mod_df = df.drop(['Fight Number', 
mod_df

col_names = {
    'Column Name': [
        'FL_DATE',                 
        'OP_CARRIER',               
        'TAIL_NUM',            
        'OP_CARRIER_FL_NUM',   
        'ORIGIN',              
        'ORIGIN_CITY_NAME',      
        'ORIGIN_STATE_NM',       
        'DEST',                  
        'DEST_CITY_NAME',        
        'DEST_STATE_NM',         
        'DEP_TIME',              
        'DEP_DELAY',             
        'DEP_DELAY_NEW',         
        'TAXI_OUT',              
        'WHEELS_OFF',            
        'WHEELS_ON',             
        'TAXI_IN',               
        'ARR_TIME',             
        'ARR_DELAY',            
        'ARR_DELAY_NEW',        
        'CANCELLED',            
        'CANCELLATION_CODE',    
        'DIVERTED',             
        'ACTUAL_ELAPSED_TIME',  
        'AIR_TIME',             
        'FLIGHTS',              
        'DISTANCE',             
        'DISTANCE_GROUP',      
        'CARRIER_DELAY',        
        'WEATHER_DELAY',        
        'NAS_DELAY',            
        'SECURITY_DELAY',       
        'LATE_AIRCRAFT_DELAY',  
        'FIRST_DEP_TIME',       
        'TOTAL_ADD_GTIME',      
        'LONGEST_ADD_GTIME',    
        'DIV_AIRPORT_LANDINGS',     
        'DIV_REACHED_DEST',         
        'DIV_ACTUAL_ELAPSED_TIME',  
        'DIV_ARR_DELAY',            
        'DIV_DISTANCE', 
    ],
    'Description': [
        'Flight Date',
        'Carrier',
        'Aircraft Tail Number',
        'Flight Number',
        'Origin Airport',
        'Origin City',
        'Origin State',
        'Destination Airport',
        'Destination City',
        'Destination State',
        'Departure Time',
        'Scheduled Dep. Time - Actual Dep. Time',
        'kdkdkdkd',
        'Amount of time to taxi to for takeoff',
        'Takeoff Time',
        'Landing Time',
        'Amount of time to taxi to the gate',
        'Arrival Time',
        'Difference in minutes between scheduled and actual arrival time',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
        'jndcjdnc',
    ]
}
col_df = pd.DataFrame(col_names)
col_df

,Flight Date,Carrier,Tail Number,Flight Number,Origin Airport,Origin City,Origin State,Destination Airport,Destination City,Destination State,...,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,FIRST_DEP_TIME,TOTAL_ADD_GTIME,LONGEST_ADD_GTIME,DIV_AIRPORT_LANDINGS,DIV_REACHED_DEST,DIV_ACTUAL_ELAPSED_TIME,DIV_ARR_DELAY,DIV_DISTANCE
0,2025-01-01,AA,N101NN,164,SFO,"San Francisco, CA",California,JFK,"New York, NY",New York,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
1,2025-01-01,AA,N101NN,76,JFK,"New York, NY",New York,SFO,"San Francisco, CA",California,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
2,2025-01-01,AA,N102UW,3244,SAT,"San Antonio, TX",Texas,CLT,"Charlotte, NC",North Carolina,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
3,2025-01-01,AA,N103NN,185,JFK,"New York, NY",New York,LAX,"Los Angeles, CA",California,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
4,2025-01-01,AA,N103NN,2455,BOS,"Boston, MA",Massachusetts,LAX,"Los Angeles, CA",California,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539742,2025-01-31,YX,N979RP,4513,LGA,"New York, NY",New York,CLE,"Cleveland, OH",Ohio,...,0.0,0.0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
539743,2025-01-31,YX,N979RP,4654,LGA,"New York, NY",New York,SDF,"Louisville, KY",Kentucky,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
539744,2025-01-31,YX,N979RP,4654,SDF,"Louisville, KY",Kentucky,LGA,"New York, NY",New York,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
539745,2025-01-31,YX,N979RP,4666,CVG,"Cincinnati, OH",Kentucky,LGA,"New York, NY",New York,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
539746,2025-01-31,YX,N979RP,4787,LGA,"New York, NY",New York,GSP,"Greer, SC",South Carolina,...,0.0,29.0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN

# 2. Data Quality
- What is broken, missing, or suspicious?
- Are the dtypes correct for each variable?
- Do the values make sense?
- Where is data missing and how much?
- Are there duplicates or outliers?
- Is the data trustworthy as is?

AttributeError: 'DataFrame' object has no attribute 'dytpes'

# 3. Cleaning Decisions
- Motivation
    - How do I fix problems without corrupting the truth?
- Questions
    - Drop or fix? What's the impact on the analysis?
    - What the missingness mechanism (MCAR / MAR / MNAR)
    - Are outliers legit or are they errors?
    - What assumptions am I making?
- Hypothesis & Iteration
    - What biases might my cleaning decisions introduce
    - What sensitivity analyses should I run?
- Iteration Signals
    - Cleaning reveals new issues --> back to phase 2
    - Decisions feel arbitrary --> need domain expertise

# 4. Statistical EDA
### Content From Lecture 13a 
-Motivation

    - What patterns, relationships stories exist in the data?
-Driving Questions

    - What's "typical" for each variable?
    - How do variables relate to each other?
    - Do patterns hold across subgroups?
    What surprises emerge?

### Project

- Motivation
    -fdfsf

- Driving Questions

# 5. Transformation

# 6. Save & Document