# Introduction
## Help

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

# Initial Questions
1. What do we want to know about airline on-time performance?
2. How will the answer be useful in decisio making?

# Data Specific Questions
1. How does on-time performance vary across carrier, airports, time, day, maybe aircraft?
    -  What's overall distribution of any flight delays?  
    -  What airline has the best and worst on-time performance?
    -  How do routes (short/long) correlate with performance?
    -  What departure time windows have the least amount of delays? Most amount of delays?
    -  What is the average delay per airport? per airline? per airport & airline?
    - What percentage of flights leave on-time? 
    -  What time ranges have the highest/lowest delays?
        - Is there any relationship between time of day and airline or airport to
    -How many flights per day?
        - By airport?
        - Percent on-time vs. delayed

2. What propagation patterns can we draw?
    - What are the ripple effects of delays?
        - Is there recovery or do they compound / propagate?
            - Are some airlines better at recovering than others?
        - Can information can we draw from taxi times? Thinking about traffic jams at the runways
    - What percent of flights are delayed 15, 30, 60+ minutes?

3. What factors have the greatest effect on on-time performance
    - Weather
        - What percentage of deas are due to weather?
        - Which airports have the highest weather delays?
        - What is the average weather delay?
        - What weather delay comes up most freuqently?
    - Secuirty
        What percentage of delays are due to security issues? 
    - Carrier
        - Which carriers have the highest delays? 
    - National Aviation System

4. What is the overall cost of delays?
    -Fuel, labor, etc. 

6. What is the impact to customers?
    - Which airports should customers expect delays
    - What percent of flights are delayed 15, 30, 60+ minutes?

# Source Data
United States Department of Transportation - U.S. Buerau of Transportation Statistics

# Features
### 1. Date

### 2. Time of Day

### 3. Carrier
- American
- United
- Delta
- Southwest
- Alaska
- JetBlue
- Spirit
- Frontier
- 
### 5. Airport (Departure)
- Dallas Fort-Worth (DFW) **1**
- Atlanta (ATL)           **2**
- Los Angeles (LAX)       **3**
- New York                **6**
  - JFK
- Miami (MIA)             **8**
- Chicago O'Hare (OHD)    **4**
- Phoenix (PHX)           **7**
- Denver (DEN)            **5**
- San Franscisco (SFO)
- Washington D.C.
  - Dulles (IAD)

**I was thinking we could just narrow it down to 5-10 airports but since we have the airport IDs in the data, I don't entirely see the benefit of just picking 10 other than maybe lessening the complexity or size of the data**
**Since we have all of the airport IDs listed in the data, maybe we could just do some groupings, maybe by U.S. region?**

### 7. Airport (Arrival)

### 8. Reason For Delay
- Weather
- Carrier
- Security
- Late Aircraft
- National Aviation System (NAS)
**we can leave these split up into their own feature**

### 9. Tail Number

### 10. Elapsed Time

### 11. State

# 1. Initial Load & Reconniassance 
## Questions to Answer
1. Tidy or not?
2. Entities, Attributes, Observations?
3. Variable Types?
4. Shape & scale?
5. Any obvious problems?

### Hypothessis

In [3]:
#depatures + arrivals dataset
df_path = Path("../data/Raw/Source_Data.zip")
df = pd.read_csv(df_path, compression="zip", parse_dates=["FL_DATE"], low_memory=False)
df

/var/folders/hz/d2mv2jxn6fl85mfk3ln_rxz80000gn/T/ipykernel_30190/321286477.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv(df_path, compression="zip", parse_dates=["FL_DATE"], low_memory=False)

,FL_DATE,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_NM,DEST,DEST_CITY_NAME,DEST_STATE_NM,...,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,FIRST_DEP_TIME,TOTAL_ADD_GTIME,LONGEST_ADD_GTIME,DIV_AIRPORT_LANDINGS,DIV_REACHED_DEST,DIV_ACTUAL_ELAPSED_TIME,DIV_ARR_DELAY,DIV_DISTANCE
0,2025-01-01,AA,N101NN,164,SFO,"San Francisco, CA",California,JFK,"New York, NY",New York,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
1,2025-01-01,AA,N101NN,76,JFK,"New York, NY",New York,SFO,"San Francisco, CA",California,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
2,2025-01-01,AA,N102UW,3244,SAT,"San Antonio, TX",Texas,CLT,"Charlotte, NC",North Carolina,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
3,2025-01-01,AA,N103NN,185,JFK,"New York, NY",New York,LAX,"Los Angeles, CA",California,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
4,2025-01-01,AA,N103NN,2455,BOS,"Boston, MA",Massachusetts,LAX,"Los Angeles, CA",California,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539742,2025-01-31,YX,N979RP,4513,LGA,"New York, NY",New York,CLE,"Cleveland, OH",Ohio,...,0.0,0.0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
539743,2025-01-31,YX,N979RP,4654,LGA,"New York, NY",New York,SDF,"Louisville, KY",Kentucky,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
539744,2025-01-31,YX,N979RP,4654,SDF,"Louisville, KY",Kentucky,LGA,"New York, NY",New York,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
539745,2025-01-31,YX,N979RP,4666,CVG,"Cincinnati, OH",Kentucky,LGA,"New York, NY",New York,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
539746,2025-01-31,YX,N979RP,4787,LGA,"New York, NY",New York,GSP,"Greer, SC",South Carolina,...,0.0,29.0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN

In [12]:
df.columns
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 539747 entries, 0 to 539746
Data columns (total 41 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   FL_DATE                  539747 non-null  datetime64[ns]
 1   OP_CARRIER               539747 non-null  object
 2   TAIL_NUM                 537217 non-null  object
 3   OP_CARRIER_FL_NUM        539747 non-null  int64
 4   ORIGIN                   539747 non-null  object
 5   ORIGIN_CITY_NAME         539747 non-null  object
 6   ORIGIN_STATE_NM          539747 non-null  object
 7   DEST                     539747 non-null  object
 8   DEST_CITY_NAME           539747 non-null  object
 9   DEST_STATE_NM            539747 non-null  object
 10  DEP_TIME                 523861 non-null  float64
 11  DEP_DELAY                523824 non-null  float64
 12  DEP_DELAY_NEW            523824 non-null  float64
 13  TAXI_OUT                 523520 non-null  float64
 14  WHEELS_OFF               523520 non-null  float64
 15  WHEELS_ON                523167 non-null  float64
 16  TAXI_IN                  523167 non-null  float64
 17  ARR_TIME                 523167 non-null  float64
 18  ARR_DELAY                522269 non-null  float64
 19  ARR_DELAY_NEW            522269 non-null  float64
 20  CANCELLED                539747 non-null  int64
 21  CANCELLATION_CODE        16312 non-null   object
 22  DIVERTED                 539747 non-null  int64
 23  ACTUAL_ELAPSED_TIME      522269 non-null  float64
 24  AIR_TIME                 522269 non-null  float64
 25  FLIGHTS                  539747 non-null  int64
 26  DISTANCE                 539747 non-null  int64
 27  DISTANCE_GROUP           539747 non-null  int64
 28  CARRIER_DELAY            98130 non-null   float64
 29  WEATHER_DELAY            98130 non-null   float64
 30  NAS_DELAY                98130 non-null   float64
 31  SECURITY_DELAY           98130 non-null   float64
 32  LATE_AIRCRAFT_DELAY      98130 non-null   float64
 33  FIRST_DEP_TIME           4267 non-null    float64
 34  TOTAL_ADD_GTIME          4267 non-null    float64
 35  LONGEST_ADD_GTIME        4267 non-null    float64
 36  DIV_AIRPORT_LANDINGS     539747 non-null  int64
 37  DIV_REACHED_DEST         1166 non-null    float64
 38  DIV_ACTUAL_ELAPSED_TIME  898 non-null     float64
 39  DIV_ARR_DELAY            898 non-null     float64
 40  DIV_DISTANCE             1166 non-null    float64
dtypes: datetime64[ns](1), float64(24), int64(7), object(9)
memory usage: 168.8+ MB

41

In [7]:
#Changing features names to be more clear
mod_df = df.rename(columns={
    'FL_DATE': 'Flight Date',
    'OP_CARRIER': 'Carrier',
    'TAIL_NUM': 'Tail Number',
    'OP_CARRIER_FL_NUM': 'Flight Number',
    'ORIGIN': 'Origin Airport',
    'ORIGIN_CITY_NAME': 'Origin City'
})
mod_df

,Flight Date,Carrier,Tail Number,Flight Number,Origin Airport,Origin City,ORIGIN_STATE_NM,DEST,DEST_CITY_NAME,DEST_STATE_NM,...,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,FIRST_DEP_TIME,TOTAL_ADD_GTIME,LONGEST_ADD_GTIME,DIV_AIRPORT_LANDINGS,DIV_REACHED_DEST,DIV_ACTUAL_ELAPSED_TIME,DIV_ARR_DELAY,DIV_DISTANCE
0,2025-01-01,AA,N101NN,164,SFO,"San Francisco, CA",California,JFK,"New York, NY",New York,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
1,2025-01-01,AA,N101NN,76,JFK,"New York, NY",New York,SFO,"San Francisco, CA",California,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
2,2025-01-01,AA,N102UW,3244,SAT,"San Antonio, TX",Texas,CLT,"Charlotte, NC",North Carolina,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
3,2025-01-01,AA,N103NN,185,JFK,"New York, NY",New York,LAX,"Los Angeles, CA",California,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
4,2025-01-01,AA,N103NN,2455,BOS,"Boston, MA",Massachusetts,LAX,"Los Angeles, CA",California,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539742,2025-01-31,YX,N979RP,4513,LGA,"New York, NY",New York,CLE,"Cleveland, OH",Ohio,...,0.0,0.0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
539743,2025-01-31,YX,N979RP,4654,LGA,"New York, NY",New York,SDF,"Louisville, KY",Kentucky,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
539744,2025-01-31,YX,N979RP,4654,SDF,"Louisville, KY",Kentucky,LGA,"New York, NY",New York,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
539745,2025-01-31,YX,N979RP,4666,CVG,"Cincinnati, OH",Kentucky,LGA,"New York, NY",New York,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
539746,2025-01-31,YX,N979RP,4787,LGA,"New York, NY",New York,GSP,"Greer, SC",South Carolina,...,0.0,29.0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN

# 2. Data Quality
- What is broken, missing, or suspicious?
- Are the dtypes correct for each variable?
- Do the values make sense?
- Where is data missing and how much?
- Are there duplicates or outliers?
- Is the data trustworthy as is?

AttributeError: 'DataFrame' object has no attribute 'dytpes'

# 3. Cleaning Decisions
- Motivation
    - How do I fix problems without corrupting the truth?
- Questions
    - Drop or fix? What's the impact on the analysis?
    - What the missingness mechanism (MCAR / MAR / MNAR)
    - Are outliers legit or are they errors?
    - What assumptions am I making?
- Hypothesis & Iteration
    - What biases might my cleaning decisions introduce
    - What sensitivity analyses should I run?
- Iteration Signals
    - Cleaning reveals new issues --> back to phase 2
    - Decisions feel arbitrary --> need domain expertise

# 4. Statistical EDA
-Motivation
    - What patterns, relationships stories exist in the data?
-Driving Questions
    - What's "typical" for each variable?
    - How do variables relate to each other?
    - Do patterns hold across subgroups?
    What surprises emerge?

# 5. Transformation

# 6. Save & Document